/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_ms.comm.JNIFUNCCALLBACK
#define _Included_com_ms.comm.JNIFUNCCALLBACK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ms.comm.JNIFUNCCALLBACK
 * Method:    JniFuncCallback
 * Signature: (I)V
 */
    
JNIEXPORT void JNICALL Java_com_ms_comm_JniFuncUtils_JniFuncCallBack
    (JNIEnv *, jobject, jstring, jstring);
    
#ifdef __cplusplus
}
#endif
#endif
